### PR TITLE
[WIP] Increase test coverage

### PR DESCRIPTION
**Pull request by groyoh**
Brings `mux` coverage to 100%.

### CODE REVIEW

**Comment by h2non** [comment]
Can I proceed with the merge?

**Comment by h2non** [comment]
I leave the branch so we can reuse it.

**Comment by groyoh** [comment]
@h2non I'm currently on sick leave so I won't necessarily be available the incoming week.

**Comment by h2non** [comment]
@groyoh Ok, thank you!

**Pull request merged**
